# Generated by Django 3.0.5 on 2021-05-11 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assylum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_type', models.CharField(blank=True, max_length=100)),
                ('org_name', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=80)),
                ('phone', models.PositiveIntegerField(blank=True)),
                ('working_day', models.CharField(blank=True, max_length=900)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('services', models.TextField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Gp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, upload_to='pics')),
                ('description', models.CharField(blank=True, max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('currenstatus', models.BooleanField(default=True)),
                ('category_type', models.CharField(blank=True, choices=[('Emergency_Support', 'Emergency_Support'), ('Fix_Meeting', 'Fix_Meeting'), ('Others', 'Others'), ('Direct_Meeting', 'Direct_Meeting')], default=True, max_length=50)),
                ('details', models.TextField(blank=True, default=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('assign', models.CharField(max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Refuse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=80)),
                ('phone', models.PositiveIntegerField(blank=True)),
                ('working_day', models.CharField(blank=True, max_length=900)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Save_value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consellor', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='WelcomeNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Querystatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED')], default='PENDING', max_length=30)),
                ('query_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Query')),
            ],
        ),
        migrations.CreateModel(
            name='Messages_Assigned',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Assigned', models.BooleanField()),
                ('Assigned_Date', models.DateTimeField(auto_now=True)),
                ('Assigned_By', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Assigned_By', to=settings.AUTH_USER_MODEL)),
                ('Assigned_To', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Assigned_To', to=settings.AUTH_USER_MODEL)),
                ('Message_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Message')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pic/CustomerProfilePic/')),
                ('mobile', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
