# Generated by Django 3.0.5 on 2021-05-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='category_type',
            field=models.CharField(blank=True, choices=[('Emergency_Support', 'Emergency_Support'), ('Fix_Meeting', 'Fix_Meeting'), ('Others', 'Others'), ('Direct_Meeting', 'Direct_Meeting')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='querystatus',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=30),
        ),
    ]
